### ISSUE TITLE
Change Brush Functionality

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#19]
Left-click (attack) should set "First point"
Right-click (use)  should set "Second point"
Shift+Left-click should cycle between forms (Circle, Cube)
Shift+Right-click should spawn selected form

I don't think players would like using commands, on most servers commands disabled in a first place.

Also, you should add "Sphere" form. Sphere is HELLA annoyong to build.

**Comment by Calemi** [comment]
I used commands to mimic World Edit. Also commands allow for an easy check for servers to see if they want everyone using the brush or just some. By default, deops can use the brush as well. There is also a config option to use permission check to use it. Since the brush can be laggy I left this option for server owners to control who gets to functionality.

If I were to remove commands, I would just end up making a GUI for the shape and color changing. But for now, I think I'll keep it the way it is.
